import 'package:flutter/material.dart';
import '../services/api_service.dart';
import '../services/app_events.dart';
import '../theme/app_colors.dart';
import '../widgets/sk_ui.dart';

class WeightScreen extends StatefulWidget { const WeightScreen({super.key}); @override State<WeightScreen> createState()=>_WeightScreenState(); }
class _WeightScreenState extends State<WeightScreen>{ final _weightCtrl=TextEditingController(); bool _loading=true; List<dynamic> _weights=[]; @override void initState(){super.initState();_load();} @override void dispose(){_weightCtrl.dispose();super.dispose();}
Future<void> _load()async{setState(()=>_loading=true);try{final w=await ApiService.getWeights();if(mounted)setState(()=>_weights=w);}catch(e){if(mounted)_toast('Không tải được cân nặng: $e');}if(mounted)setState(()=>_loading=false);} Future<void> _save()async{final w=double.tryParse(_weightCtrl.text);if(w==null||w<=0){_toast('Cân nặng không hợp lệ');return;}final r=await ApiService.addWeight(w,date:ApiService.localDateKey());if(r['success']==true){AppEvents.notifyDataChanged();_weightCtrl.clear();_load();}else{_toast(r['message']??'Không lưu được cân nặng');}} void _toast(String m)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(m)));
@override Widget build(BuildContext context){return Scaffold(backgroundColor:AppColors.background,body:SafeArea(child:ListView(padding:const EdgeInsets.fromLTRB(20,14,20,30),children:[Row(children:[IconButton(onPressed:()=>Navigator.pop(context),icon:const Icon(Icons.arrow_back_rounded)),const Expanded(child:Text('Theo dõi cân nặng',style:TextStyle(color:AppColors.textDark,fontSize:24,fontWeight:FontWeight.w900)))]),const SizedBox(height:12),SkCard(child:Column(children:[SkTextField(controller:_weightCtrl,label:'Cân nặng hiện tại',hint:'kg',keyboardType:TextInputType.number),const SizedBox(height:16),SkPrimaryButton(label:'Lưu cân nặng',icon:Icons.save_rounded,onPressed:_save)])),const SizedBox(height:16),SkCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Lịch sử',style:TextStyle(color:AppColors.textDark,fontSize:18,fontWeight:FontWeight.w900)),const SizedBox(height:10),if(_loading)const Center(child:CircularProgressIndicator(color:AppColors.primary))else if(_weights.isEmpty)const Text('Chưa có dữ liệu',style:TextStyle(color:AppColors.textGrey))else ..._weights.reversed.map((x){final m=Map<String,dynamic>.from(x as Map);return ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.monitor_weight_rounded,color:AppColors.primary),title:Text('${NumFmt.whole(m['weight_kg']??m['weight'])} kg'),subtitle:Text('${m['log_date']??''}'));})]))])));}}
